steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/receipt-reader-bot", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/receipt-reader-bot"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "receipt-reader-bot"
      - "--image"
      - "gcr.io/$PROJECT_ID/receipt-reader-bot"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--update-secrets"
      - "TELEGRAM_TOKEN=TELEGRAM_TOKEN:latest"
      - "--update-secrets"
      - "OPENAI_API_KEY=OPENAI_API_KEY:latest"
      - "--update-secrets"
      - "WEBHOOK_URL=WEBHOOK_URL:latest"
      - "--update-secrets"
      - "GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest"
      - "--update-secrets"
      - "GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest"
      - "--update-secrets"
      - "GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest"

images:
  - "gcr.io/$PROJECT_ID/receipt-reader-bot"
